# Generated by Django 2.1.7 on 2019-03-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зала')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=15, verbose_name='Номер ряда')),
                ('place', models.CharField(max_length=15, verbose_name='Номер места')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sitting_hall', to='webapp.Hall', verbose_name='Название зала')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('finish_datetime', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall', to='webapp.Hall', verbose_name='Название зала')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='webapp.Movie', verbose_name='Название фильма')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='category', to='webapp.Category', verbose_name='Жанр'),
        ),
    ]
