# Generated by Django 2.1.7 on 2019-03-06 16:12

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190306_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default=webapp.models.generate_code, editable=False, max_length=12, unique_for_date='created_at'),
        ),
    ]
