# Generated by Django 2.1.7 on 2019-03-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190306_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sale',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='webapp.Sale', verbose_name='Скидка'),
        ),
    ]
