# Generated by Django 2.1.7 on 2019-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190306_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='sale',
            name='how',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
